### ISSUE TITLE
请问攻击算法中的ODFA算法的代码实现的位置？

### ISSUE THREAD

**Issue by HazeFlood** [luzhixing12345/Evaluation-of-attack-and-defense-strategies-for-Reid#1]
如题，我在您的use.md中看到命令行可以调用ODFA算法，但是在attack_patch下的攻击算法中没有找到ODFA算法的代码，所以想问一下:)

**Comment by luzhixing12345** [comment]
https://github.com/luzhixing12345/Evaluation-of-attack-and-defense-strategies-for-Reid/blob/bde309e44a6496944a6ebbd18a44cec04a024594/fastreid/utils/attack_patch/attack_type/QA.py#L141

ODFA算法基本实现与IFGSM比较类似，主要区别是targeted=not self.target和它的loss_fn的定义

https://github.com/luzhixing12345/Evaluation-of-attack-and-defense-strategies-for-Reid/blob/bde309e44a6496944a6ebbd18a44cec04a024594/fastreid/utils/attack_patch/attack_type/QA.py#L128-L133
